### ISSUE TITLE
选择本地照片时没有全选按钮

### ISSUE THREAD

**Issue by freeze-code** [fregie/pho#16]
大佬厉害，做的这个APP可以说是我梦想中可以与NAS同步的相册的样子了，佩服！

在使用时发现，照片貌似只能一张一张选择，无法全选，是我没找到按钮还是目前无此功能呢？

**Comment by fregie** [comment]
没有全选按钮。
要上传全部图片用同步功能，会自动上传全部

**Comment by freeze-code** [comment]
这样啊，我是在选择某一相册文件夹的所有图片时遇到的，只能全选的话不想上传的文件夹也会上传了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月17日(周六) 晚上7:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fregie/pho] 选择本地照片时没有全选按钮 (Issue #16)




 
没有全选按钮。
 要上传全部图片用同步功能，会自动上传全部

**Comment by fregie** [comment]
同步功能只会同步当前选中文件夹的所有图片.
