### ISSUE TITLE
关于thumbnail 生成问题

### ISSUE THREAD

**Issue by ChitaGideon** [fregie/pho#17]
如果我直接用webdav 网上的相册，
那本地缩略图生成逻辑是什么？需要全部把webdav上的图片下下来再生成缩略图吗？

**Comment by fregie** [comment]
webdav上已有的照片正常来说不会在app里显示，从本地上传照片的时候会按一定的目录结构组织，读取云端的时候也会按照这个目录结构，不符合对应目录结构的不能正常工作

**Comment by ChitaGideon** [comment]
所以这个云端照片查看是 什么意思呢，是指把云端同步到本地之后再查看么

**Comment by fregie** [comment]
把本地同步到云端再看
