### ISSUE TITLE
关于项目中包含server部分代码的疑问

### ISSUE THREAD

**Issue by danlanxiaohei** [fregie/pho#2]
有个疑问咨询下，就是server目录下是使用go实现的一个gRPC服务，但是介绍中，说这是一个【无服务端】的项目，理解起来稍微有点歧义。另外就是，server文件夹里的代码是不是最好单独放在另外一个repository？（因为flutter开发者多数是客户端开发者，项目里放着服务端的代码，多少会让他们觉得【不安】？）

**Comment by fregie** [comment]
server只是用go实现一部分客户端核心逻辑,只是客户端调用的方式是通过grpc.它是跑在app里的,并非通俗意义上的"服务端"

**Comment by danlanxiaohei** [comment]
了解了～感谢
