### ISSUE TITLE
更新photoprism后（4月20日版本），启用两步验证后，pho再用webDAV连报错

### ISSUE THREAD

**Issue by nothstern** [fregie/pho#62]
[PhotoPrism® 
Build [240420-ef5f14bc4]
![屏幕截图 2024-04-22 142708](https://github.com/fregie/pho/assets/61000609/c1a58bbc-9e04-4740-a2ef-8ab666913fbb)

![c5a85c9ba3e6faa400df1c704c46f54](https://github.com/fregie/pho/assets/61000609/05dc1849-1d13-4f04-a429-1141f0004321)

**Comment by troilus** [comment]
可以试一下在photoprism中生成应用专用密码，我没有配置photoprism的webdav所以没法尝试

**Comment by nothstern** [comment]
> 可以试一下在photoprism中生成应用专用密码，我没有配置photoprism的webdav所以没法尝试
可以了，赞
